project_id = "lfkopushsjqigxiafior"

[functions.notify-application]
verify_jwt = false

[functions.get-analytics]
verify_jwt = true

[functions.manage-community]
verify_jwt = true

[functions.user-profile-management]
verify_jwt = true

[functions.search-alumni]
verify_jwt = true

[functions.apply-for-referral]
verify_jwt = true

[functions.update-application-status]
verify_jwt = true

[functions.get-community-feed]
verify_jwt = true

[functions.toggle-post-like]
verify_jwt = true

[functions.manage-user-role]
verify_jwt = true
